import type {
  BlogPost,
  EquipmentItem,
  Industry,
  Project,
  Service,
  SiteStat,
} from '@/types';

export const siteStats: SiteStat[] = [
  { label: 'What We Deliver', value: '01' },
  { label: 'Aerial Site Mapping', value: '02' },
  { label: 'High-Resolution Orthomosaics', value: '03' },
  { label: '2D & 3D Site Outputs', value: '04' },
];

export const services: Service[] = [
  {
    slug: 'photogrammetry',
    name: 'Photogrammetry',
    description: 'High-overlap aerial image capture for orthomosaics, meshes, and terrain models.',
    applications: ['Planning', 'Progress tracking', 'Asset documentation'],
    deliverables: ['Orthomosaic', '3D mesh', 'DEM'],
    estimatedTurnaround: '2-5 days',
  },
  {
    slug: 'lidar-survey',
    name: 'LiDAR Survey',
    description: 'Laser scanning workflows for high-density point clouds in complex or vegetated terrain.',
    applications: ['Corridors', 'Forested sites', 'Utilities'],
    deliverables: ['Classified LAS', 'DTM', 'DSM'],
    estimatedTurnaround: '3-7 days',
  },
  {
    slug: 'orthomosaic-mapping',
    name: 'Orthomosaic Mapping',
    description: 'Accurate, geo-referenced aerial mosaics for measurement and site review.',
    applications: ['Construction', 'Architecture', 'Site documentation'],
    deliverables: ['Orthomosaic TIFF', 'Web tiles', 'Annotations'],
    estimatedTurnaround: '2-4 days',
  },
  {
    slug: 'dem-dsm-generation',
    name: 'DEM & DSM Generation',
    description: 'Surface and terrain models for grading, drainage, and design validation.',
    applications: ['Civil design', 'Earthworks', 'Hydrology'],
    deliverables: ['DEM', 'DSM', 'Contours'],
    estimatedTurnaround: '3-5 days',
  },
  {
    slug: 'contour-mapping',
    name: 'Contour Mapping',
    description: 'Topographic contour extraction aligned to project tolerances and design needs.',
    applications: ['Land development', 'Roads', 'Planning'],
    deliverables: ['Contour CAD', 'Breaklines', 'QA report'],
    estimatedTurnaround: '3-6 days',
  },
  {
    slug: '3d-modeling',
    name: '3D Modeling',
    description: 'Terrain and site models for visualization, basic measurements, and coordination.',
    applications: ['Design review', 'Architecture', 'Stakeholder communication'],
    deliverables: ['Mesh', 'Textured model', 'Viewer package'],
    estimatedTurnaround: '4-7 days',
  },
  {
    slug: 'construction-monitoring',
    name: 'Construction Monitoring',
    description: 'Repeatable capture schedules for progress visualization and organized reporting.',
    applications: ['Weekly updates', 'Site records', 'Schedule visibility'],
    deliverables: ['Progress dashboards', 'Timelapse views', 'Reports'],
    estimatedTurnaround: '24-48 hours',
  },
  {
    slug: 'mining-survey',
    name: 'Mining Survey',
    description: 'Stockpile volumes, pit mapping, and haul-road visibility for mining operations.',
    applications: ['Volume reviews', 'Safety reviews', 'Planning'],
    deliverables: ['Volumes', 'Surface models', 'Annotated orthos'],
    estimatedTurnaround: '1-3 days',
  },
  {
    slug: 'infrastructure-inspection',
    name: 'Infrastructure Inspection',
    description: 'Visual and geospatial inspection support for roads, bridges, and utilities.',
    applications: ['Condition monitoring', 'Maintenance planning', 'Audit trails'],
    deliverables: ['Inspection imagery', 'Defect maps', 'Reports'],
    estimatedTurnaround: '2-5 days',
  },
  {
    slug: 'agricultural-mapping',
    name: 'Agricultural Mapping',
    description: 'Field-scale capture for terrain, irrigation, and crop-support analysis.',
    applications: ['Drainage', 'Canopy analysis', 'Land management'],
    deliverables: ['Vegetation layers', 'Terrain models', 'Field maps'],
    estimatedTurnaround: '2-4 days',
  },
  {
    slug: 'volume-calculations',
    name: 'Volume Calculations',
    description: 'Volume estimates for stockpiles, cut/fill balances, and earthworks review.',
    applications: ['Quarries', 'Construction', 'Materials management'],
    deliverables: ['Volume tables', 'Cross sections', 'Comparison reports'],
    estimatedTurnaround: '24 hours',
  },
];

export const projects: Project[] = [
  {
    slug: 'site-mapping-package',
    name: 'Site Mapping Package',
    overview:
      'Example output set for aerial site surveying, high-resolution orthomosaic generation, and organized project handoff.',
    clientIndustry: 'Architecture & Construction',
    location: 'Planning, design, and site coordination workflows',
    surveyArea: 'Adapted to the site footprint and required deliverables',
    droneUsed: 'DJI Matrice 350 RTK',
    sensorUsed: 'Zenmuse L2',
    accuracy: 'Processing and control strategy tailored to project requirements',
    deliverables: ['Orthomosaic', '2D site map', 'CAD/PDF export', 'Processed aerial dataset'],
    outcomes: [
      'Clear visual site context',
      'Measurement-ready mapping outputs',
      'Professional handoff for design and planning teams',
    ],
    gallery: ['Aerial site overview', 'Processed orthomosaic output', 'Annotated site map', 'Deliverable package summary'],
    beforeLabel: 'Raw aerial capture',
    afterLabel: 'Processed mapping deliverables',
    pin: { left: '32%', top: '54%' },
  },
  {
    slug: 'orthomosaic-measurement-package',
    name: 'Orthomosaic Measurement Package',
    overview:
      'Example deliverable package focused on high-resolution orthomosaics, 2D outputs, and area or distance measurement support.',
    clientIndustry: 'Site Planning & Documentation',
    location: 'Architecture, engineering, and construction review use cases',
    surveyArea: 'Configured to match site scope and output needs',
    droneUsed: 'DJI M350 RTK',
    sensorUsed: 'P1 + RTK network',
    accuracy: 'Output quality guided by overlap, control, and processing workflow',
    deliverables: ['Orthomosaic tiles', 'Area measurements', 'Distance checks', 'PDF markup set'],
    outcomes: [
      'High-resolution site visualization',
      'Measurement support from processed data',
      'Clean deliverables for stakeholder review',
    ],
    gallery: ['Orthomosaic tile set', 'Measurement overlay', 'Markup-ready PDF export', 'Processed image grid'],
    beforeLabel: 'Individual aerial images',
    afterLabel: 'Usable mapped output',
    pin: { left: '54%', top: '38%' },
  },
  {
    slug: '3d-visualization-package',
    name: '3D Visualization Package',
    overview:
      'Example workflow for turning aerial capture into 3D models, visual context, and presentation-ready deliverables.',
    clientIndustry: 'Architecture, Development & Construction',
    location: 'Concept review, planning, and communication workflows',
    surveyArea: 'Adaptable to buildings, land parcels, and development zones',
    droneUsed: 'DJI Mavic 3 Enterprise',
    sensorUsed: 'Mechanical shutter RGB',
    accuracy: 'Model detail depends on flight planning, control, and final output requirements',
    deliverables: ['3D model', 'Surface visualization', 'PDF snapshots', 'Client-ready presentation assets'],
    outcomes: [
      'Better spatial understanding',
      'Useful visuals for planning conversations',
      'Structured outputs from capture through final delivery',
    ],
    gallery: ['3D site model view', 'Surface visualization', 'Presentation snapshot set', 'Output handoff package'],
    beforeLabel: 'Unprocessed visual data',
    afterLabel: 'Structured 3D outputs',
    pin: { left: '44%', top: '66%' },
  },
];

export const industries: Industry[] = [
  { slug: 'construction', name: 'Construction', summary: 'Progress capture, earthworks, and stakeholder-ready reporting.', challenges: ['Schedule compression', 'Change tracking', 'Site logistics'], outputs: ['Progress maps', 'Cut/fill', 'As-built surfaces'] },
  { slug: 'architecture', name: 'Architecture', summary: 'Context capture and terrain understanding before design decisions.', challenges: ['Incomplete context', 'Manual base data', 'Visualization gaps'], outputs: ['Base maps', '3D site models', 'Context imagery'] },
  { slug: 'mining', name: 'Mining', summary: 'Volumes, haul-road monitoring, and pit mapping for ongoing site visibility.', challenges: ['Safety exposure', 'Frequent changes', 'Material accounting'], outputs: ['Volumes', 'Surface models', 'Orthomosaics'] },
  { slug: 'agriculture', name: 'Agriculture', summary: 'Terrain, irrigation, and field intelligence for large land parcels.', challenges: ['Water management', 'Field access', 'Large coverage'], outputs: ['Field maps', 'Terrain layers', 'Canopy datasets'] },
  { slug: 'roads', name: 'Roads', summary: 'Linear asset documentation and site review for roadway projects.', challenges: ['Long corridors', 'Traffic access', 'Drainage checks'], outputs: ['Corridor mosaics', 'Cross sections', 'Inspection imagery'] },
  { slug: 'railways', name: 'Railways', summary: 'Alignment review and embankment documentation for rail infrastructure teams.', challenges: ['Access windows', 'Long distances', 'Critical tolerances'], outputs: ['Contours', 'Orthomosaics', 'As-built reviews'] },
  { slug: 'power-lines', name: 'Power Lines', summary: 'Inspection and corridor awareness for utilities and right-of-way teams.', challenges: ['Vegetation risk', 'Remote access', 'Asset traceability'], outputs: ['Inspection datasets', 'Corridor models', 'Condition maps'] },
  { slug: 'solar-farms', name: 'Solar Farms', summary: 'Grading, block layout, and construction visibility for large solar sites.', challenges: ['Large footprints', 'Frequent updates', 'Drainage control'], outputs: ['Progress dashboards', 'Terrain models', 'Issue maps'] },
  { slug: 'real-estate', name: 'Real Estate', summary: 'Aerial context with planning-grade site understanding.', challenges: ['Stakeholder clarity', 'Fast proposals', 'Context communication'], outputs: ['Aerials', 'Base maps', '3D context'] },
  { slug: 'government', name: 'Government', summary: 'Geospatial capture for planning, inspection, and public works.', challenges: ['Procurement rigor', 'Auditability', 'Large territories'], outputs: ['Survey packages', 'Inspection records', 'Public works maps'] },
  { slug: 'environmental-monitoring', name: 'Environmental Monitoring', summary: 'Repeatable site observation for land, canopy, and change over time.', challenges: ['Sensitive areas', 'Dense vegetation', 'Temporal comparison'], outputs: ['LiDAR classification', 'Change layers', 'Terrain products'] },
];

export const equipment: EquipmentItem[] = [
  {
    name: 'DJI Matrice 350 RTK',
    category: 'Drone',
    specifications: ['55 min max flight time', 'IP55 weather resistance', 'Multi-payload support'],
    applications: ['LiDAR capture', 'Corridor missions', 'Large-area mapping'],
    accuracy: 'RTK-enabled mission control',
    range: '20 km video transmission',
    payload: '2.7 kg',
    sampleDataset: 'Utility corridor mission set',
  },
  {
    name: 'Zenmuse L2',
    category: 'LiDAR',
    specifications: ['Integrated IMU', 'RGB support', 'High-density capture'],
    applications: ['Vegetation penetration', 'DTM/DSM', 'Corridor scanning'],
    accuracy: '5 cm vertical class accuracy',
    range: '250 m effective',
    payload: 'Integrated payload',
    sampleDataset: 'Forested terrain point cloud',
  },
  {
    name: 'DJI Zenmuse P1',
    category: 'Camera Systems',
    specifications: ['Full-frame sensor', 'Mechanical shutter', '45 MP'],
    applications: ['Photogrammetry', 'Orthomosaics', 'Construction capture'],
    accuracy: 'Centimeter-grade with RTK/GCP workflow',
    range: 'Mission dependent',
    payload: 'Integrated payload',
    sampleDataset: 'Construction orthomosaic block',
  },
  {
    name: 'Emlid Reach RS3',
    category: 'RTK GPS',
    specifications: ['Multi-band GNSS', 'Tilt compensation', 'NTRIP support'],
    applications: ['GCP capture', 'Check points', 'Control surveys'],
    accuracy: 'Centimeter grade',
    range: 'Base/rover dependent',
    payload: 'Handheld field unit',
    sampleDataset: 'Ground control package',
  },
  {
    name: 'Trimble R12i',
    category: 'GNSS',
    specifications: ['IMU tilt compensation', 'Multi-constellation', 'Survey-grade rover'],
    applications: ['Control establishment', 'Verification', 'Stakeout support'],
    accuracy: 'Survey grade',
    range: 'Base/rover dependent',
    payload: 'Field rover',
    sampleDataset: 'Topographic check set',
  },
  {
    name: 'Bentley / Esri Processing Stack',
    category: 'Processing Software',
    specifications: ['Point cloud processing', 'GIS publishing', 'QA/QC workflows'],
    applications: ['Classification', 'Deliverable packaging', 'Cloud sharing'],
    accuracy: 'Pipeline dependent',
    range: 'Desktop + cloud environment',
    payload: 'Software suite',
    sampleDataset: 'Published terrain viewer',
  },
];

export const blogPosts: BlogPost[] = [
  {
    slug: 'photogrammetry-vs-lidar',
    title: 'Photogrammetry vs LiDAR: Which Survey Method Fits Your Site?',
    excerpt: 'A practical comparison of surface reconstruction, vegetation handling, budget, and speed.',
    category: 'Methods',
  },
  {
    slug: 'drone-survey-accuracy',
    title: 'What Actually Controls Drone Survey Accuracy?',
    excerpt: 'Mission planning, overlap, GCP strategy, RTK/PPK configuration, and QA are the real levers.',
    category: 'Accuracy',
  },
  {
    slug: 'construction-mapping-playbook',
    title: 'A Construction Mapping Playbook for Weekly Progress Intelligence',
    excerpt: 'How repeatable capture, cut/fill reporting, and site dashboards keep teams aligned.',
    category: 'Construction',
  },
  {
    slug: 'rtk-vs-ppk',
    title: 'RTK vs PPK in Drone Surveying',
    excerpt: 'Where each workflow shines and how they affect field speed, redundancy, and confidence.',
    category: 'GNSS',
  },
  {
    slug: 'topographic-survey-guide',
    title: 'A Buyer’s Guide to Modern Topographic Surveys',
    excerpt: 'What to ask for in scope, outputs, accuracy statements, and turnaround expectations.',
    category: 'Guide',
  },
];
